# Site settings
title: Payments Reference
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Payments Reference is not formally affiliated or sponsored by any company. It is written by people who want to make payments safer and easier for everyone.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://payments-reference.org" # the base hostname & protocol for your site
hostname: "payments-reference.org"
# twitter_username: jekyllrb
github_username: payments-reference

exclude: [vendor]

# Build settings
markdown: kramdown

nav:
  - title: Glossary
    path: /glossary/
  - title: Payment Cards
    path: /payment-cards/
    sublist:
    - title: Declines
      path: /payment-cards/declines/
    - title: PCI Compliance
      path: /payment-cards/pci-compliance/
      sublist:
        - title: SAQs
          path: /payment-cards/pci-compliance/saqs/
        - title: Integrations
          path: /payment-cards/pci-compliance/integrations/
        - title: Front-end
          path: /payment-cards/pci-compliance/front-end/
        - title: Levels
          path: /payment-cards/pci-compliance/levels/
  - title: Cryptocurrency
    path: /cryptocurrency/
